---
title: 十四、异常处理
date: 2021-06-27 00:26:40
tags: [GO]
---
**程序异常怎么办？？？处理它！！！**

<!--more-->

# defer
- 延迟执行
- 多个延迟语句时，在外层函数结束时，按照从下往上的顺序依次执行

```go
defer fmt.Println("111") 
defer fmt.Println("222") 
// 先执行222 再执行 111
```

# panic
- 中断程序运行，主动抛出错误

```go
panic("主动抛出错误")
```

# recover
- 不中断程序运行
- 有错误返回错误，无错误返回nil

```go
func main() {
    defer func() {
		if err := recover(); err != nil {
			fmt.Println(err) 
			// 捕获到下方抛出的异常 “出错误了” 并恢复程序运行
			// 可以在此处做异常处理逻辑
		}
	}()
	panic("出错误了") // 主动抛出异常并结束程序
}
```